import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { StockAnalysis, EsgAnalysis, MacroAnalysis, NewsAnalysis, LeadershipAnalysis, GroundingSource, RiskAnalysis, CompetitiveAnalysis, SectorAnalysis, CorporateCalendarAnalysis, CalculatedMetric, ExecutionStep, ChiefAnalystCritique, MarketSentimentAnalysis, FinancialMetrics } from '../types';

// --- Color and Font Definitions for a Professional Theme ---
const COLORS = {
    HEADER_BG: '#1E293B', // slate-800
    HEADER_TEXT: '#FFFFFF',
    PRIMARY_TEXT: '#0F172A', // slate-900
    SECONDARY_TEXT: '#64748B', // slate-500
    ACCENT_BLUE: '#2563EB', // blue-600
    BORDER_LIGHT: '#E2E8F0', // slate-200
    CODE_BG: '#F1F5F9', // slate-100
    WHITE: '#FFFFFF',
    RED: '#DC2626', // red-600
    GREEN: '#16A34A', // green-600
    YELLOW: '#CA8A04', // yellow-600
    ORANGE: '#EA580C', // orange-600
};

const FONT_SIZES = {
    H1: 22,
    H2: 16,
    H3: 12,
    BODY: 10,
    SMALL: 8
};

const getFilenameTimestamp = (): string => {
    const d = new Date();
    const pad = (n: number) => n.toString().padStart(2, '0');
    return `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}_${pad(d.getHours())}${pad(d.getMinutes())}`;
}

const formatPrice = (price: number | null, currencySymbol: string): string => {
    if (price === null || isNaN(price)) return 'N/A';
    return `${currencySymbol}${price.toFixed(2)}`;
};

const getMetricValue = (metric: CalculatedMetric | number | string | null): string => {
    if (metric === null || metric === undefined) return 'N/A';
    if (typeof metric === 'string') return metric;
    if (typeof metric === 'number') return metric.toFixed(2);
    if (metric && typeof metric === 'object' && 'value' in metric) {
        return metric.value !== null ? metric.value.toFixed(2) : 'N/A';
    }
    return 'N/A';
};

const formatDate = (dateString?: string): string | null => {
    if (!dateString) return null;
    try {
        const date = new Date(dateString);
        if (isNaN(date.getTime())) return null;
        return date.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
    } catch (e) {
        return null;
    }
};

class PdfBuilder {
  private doc: jsPDF;
  private y: number;
  private readonly pageHeight: number;
  private readonly pageWidth: number;
  private readonly margin: number = 30;
  private readonly contentWidth: number;
  private headerTitle: string = '';

  constructor(title: string) {
    this.doc = new jsPDF({ orientation: 'p', unit: 'pt', format: 'a4' });
    this.pageHeight = this.doc.internal.pageSize.getHeight();
    this.pageWidth = this.doc.internal.pageSize.getWidth();
    this.contentWidth = this.pageWidth - this.margin * 2;
    this.y = this.margin;
    this.headerTitle = title;
  }
  
  private addPageIfNeeded(requiredHeight: number) {
    if (this.y + requiredHeight > this.pageHeight - this.margin) {
      this.doc.addPage();
      this.y = this.margin + 20; // Extra top margin on new pages
    }
  }

  private addHeadersAndFooters() {
      const pageCount = this.doc.internal.pages.length;
      for (let i = 1; i <= pageCount; i++) {
          this.doc.setPage(i);
          
          // Header
          this.doc.setFontSize(FONT_SIZES.SMALL);
          this.doc.setFont('helvetica', 'bold');
          this.doc.setTextColor(COLORS.SECONDARY_TEXT);
          this.doc.text(this.headerTitle, this.margin, this.margin - 15);
          this.doc.setDrawColor(COLORS.BORDER_LIGHT);
          this.doc.line(this.margin, this.margin-5, this.pageWidth - this.margin, this.margin-5);
          
          // Footer
          const pageStr = `Page ${i} of ${pageCount}`;
          this.doc.setDrawColor(COLORS.BORDER_LIGHT);
          this.doc.line(this.margin, this.pageHeight - this.margin, this.pageWidth - this.margin, this.pageHeight - this.margin);
          this.doc.setTextColor(COLORS.SECONDARY_TEXT);
          this.doc.text(pageStr, this.pageWidth - this.margin - this.doc.getTextWidth(pageStr), this.pageHeight - this.margin + 15);
          this.doc.text('AG Generated by Agentic Financial Analyst', this.margin, this.pageHeight - this.margin + 15);
      }
  }

  buildTitlePage(mainTitle: string, subTitle: string) {
    this.y = this.pageHeight / 3;
    
    this.doc.setFontSize(32);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(COLORS.PRIMARY_TEXT);
    this.doc.text(mainTitle, this.pageWidth / 2, this.y, { align: 'center' });
    this.y += 40;

    this.doc.setFontSize(18);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(COLORS.SECONDARY_TEXT);
    this.doc.text(subTitle, this.pageWidth / 2, this.y, { align: 'center' });
    this.y += 80;
    
    this.doc.setFontSize(FONT_SIZES.BODY);
    this.doc.text(`Generated on: ${new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}`, this.pageWidth / 2, this.y, { align: 'center' });
    
    this.doc.addPage();
    this.y = this.margin + 20;
  }

  addSectionTitle(text: string) {
    this.addPageIfNeeded(40);
    this.doc.setFontSize(FONT_SIZES.H2);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(COLORS.PRIMARY_TEXT);
    this.doc.text(text, this.margin, this.y);
    this.y += 25;
  }

  addSubsectionTitle(text: string) {
      this.addPageIfNeeded(30);
      this.doc.setFontSize(FONT_SIZES.H3);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(COLORS.ACCENT_BLUE);
      this.doc.text(text, this.margin, this.y);
      this.y += 18;
  }
  
  addBodyText(text: string | null | undefined, options: { isPreformatted?: boolean } = {}) {
    const sanitizedText = String(text || '').replace(/[\u2018\u2019]/g, "'").replace(/[\u201C\u201D]/g, '"');
    if (!sanitizedText) return;

    this.doc.setFontSize(FONT_SIZES.BODY);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(COLORS.PRIMARY_TEXT);
    const lines = this.doc.splitTextToSize(sanitizedText, this.contentWidth);
    this.addPageIfNeeded(lines.length * 12 + 10);
    this.doc.text(lines, this.margin, this.y);
    this.y += lines.length * 12 + 10;
  }

  addBulletedList(title: string, items: string[] | undefined, iconPrefix: 'positive' | 'negative' | 'neutral' = 'neutral') {
      if (!items || items.length === 0) return;
      this.addPageIfNeeded(20 + items.length * 15);
      
      const colors = {
          positive: COLORS.GREEN,
          negative: COLORS.RED,
          neutral: COLORS.PRIMARY_TEXT
      };
      
      this.doc.setFontSize(FONT_SIZES.BODY);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(colors[iconPrefix]);
      this.doc.text(title, this.margin, this.y);
      this.y += 15;

      items.forEach(item => {
          this.doc.setFont('helvetica', 'normal');
          this.doc.setTextColor(COLORS.PRIMARY_TEXT);
          const lines = this.doc.splitTextToSize(`• ${item}`, this.contentWidth - 10);
          this.addPageIfNeeded(lines.length * 12);
          this.doc.text(lines, this.margin + 10, this.y);
          this.y += lines.length * 12;
      });
      this.addSpacer(10);
  }
  
  addKeyValueGrid(data: Record<string, string | null | undefined>) {
    const entries = Object.entries(data).filter(([, value]) => value);
    if (entries.length === 0) return;

    const boxHeight = 40;
    const boxWidth = this.contentWidth / 3 - 5;
    this.addPageIfNeeded(boxHeight + 10);
    
    entries.forEach(([key, value], index) => {
      const x = this.margin + (index % 3) * (boxWidth + 7.5);
      if (index > 0 && index % 3 === 0) {
        this.y += boxHeight + 10;
        this.addPageIfNeeded(boxHeight + 10);
      }
      
      this.doc.setDrawColor(COLORS.BORDER_LIGHT);
      this.doc.roundedRect(x, this.y, boxWidth, boxHeight, 3, 3, 'S');

      this.doc.setFontSize(FONT_SIZES.SMALL);
      this.doc.setTextColor(COLORS.SECONDARY_TEXT);
      this.doc.text(key, x + 5, this.y + 12);
      
      this.doc.setFontSize(FONT_SIZES.BODY);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(COLORS.PRIMARY_TEXT);
      this.doc.text(String(value || 'N/A'), x + 5, this.y + 28);
    });
    
    this.y += boxHeight + 15;
  }


  addSourceList(sources: GroundingSource[]) {
    this.addPageIfNeeded(20 + sources.length * 15);
    this.doc.setFontSize(FONT_SIZES.SMALL);
    sources.forEach(source => {
        const text = `• ${source.title || source.uri}`;
        const lines = this.doc.splitTextToSize(text, this.contentWidth);
        this.addPageIfNeeded(lines.length * 10 + 5);
        this.doc.setTextColor(COLORS.ACCENT_BLUE);
        this.doc.textWithLink(lines[0], this.margin + 10, this.y, { url: source.uri });
        if (lines.length > 1) {
            this.doc.text(lines.slice(1), this.margin + 10, this.y + 10);
        }
        this.y += lines.length * 10 + 5;
    });
    this.addSpacer(10);
  }

  addCodeBlock(text: string | undefined) {
    if (!text) return;
    let prettyText = text;
    try {
        // Text might already be a formatted JSON string, parse and re-stringify to ensure consistent formatting.
        prettyText = JSON.stringify(JSON.parse(text), null, 2);
    } catch (e) { /* Not valid JSON, use the text as is */ }

    const lines = this.doc.splitTextToSize(prettyText, this.contentWidth - 20);
    const rectHeight = lines.length * 9 + 20; // Using 9 for Courier font size + line spacing
    this.addPageIfNeeded(rectHeight + 10);
    
    this.doc.setFillColor(COLORS.CODE_BG);
    this.doc.setDrawColor(COLORS.BORDER_LIGHT);
    this.doc.roundedRect(this.margin, this.y, this.contentWidth, rectHeight, 5, 5, 'FD');
    
    this.doc.setFont('courier', 'normal');
    this.doc.setFontSize(FONT_SIZES.SMALL);
    this.doc.setTextColor(COLORS.PRIMARY_TEXT);
    this.doc.text(lines, this.margin + 10, this.y + 15);
    this.y += rectHeight + 15;
  }
  
  addStep(step: ExecutionStep) {
    const stepTitle = `${step.agentKey.toUpperCase()}: ${step.stepName}`;
    const statusText = step.status.charAt(0).toUpperCase() + step.status.slice(1);
    
    const inputLines = step.input ? this.doc.splitTextToSize(step.input, this.contentWidth - 20).length : 0;
    const outputLines = step.output ? this.doc.splitTextToSize(step.output, this.contentWidth - 20).length : 0;
    const requiredHeight = 50 + (inputLines * 9) + (outputLines * 9);
    this.addPageIfNeeded(requiredHeight);

    this.doc.setDrawColor(COLORS.BORDER_LIGHT);
    this.doc.line(this.margin, this.y, this.pageWidth - this.margin, this.y);
    this.y += 15;

    this.doc.setFontSize(FONT_SIZES.H3);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(COLORS.PRIMARY_TEXT);
    this.doc.text(stepTitle, this.margin, this.y);

    const statusWidth = this.doc.getTextWidth(statusText);
    this.doc.setFontSize(FONT_SIZES.SMALL);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(COLORS.SECONDARY_TEXT);
    this.doc.text(statusText, this.pageWidth - this.margin - statusWidth, this.y);
    
    this.y += 20;

    if (step.input) {
        this.addSubsectionTitle('Input');
        this.addCodeBlock(step.input);
    }
    if (step.output) {
        this.addSubsectionTitle('Output');
        this.addCodeBlock(step.output);
    }
    
    this.addSpacer(10);
  }
  
  addKeyInsightBox(title: string, value: string, color: string, x: number, boxWidth: number, boxHeight: number) {
    this.doc.setFontSize(FONT_SIZES.SMALL);
    this.doc.setTextColor(COLORS.SECONDARY_TEXT);
    this.doc.text(title, x + 10, this.y + 15);
    
    this.doc.setFontSize(FONT_SIZES.H3);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(color);
    this.doc.text(value, x + 10, this.y + 35);
  }

  addKeyInsightsGrid(analysisResult: StockAnalysis, currencySymbol: string) {
    const boxWidth = this.contentWidth / 4 - 5;
    const boxHeight = 50;
    this.addPageIfNeeded(boxHeight + 20);
    const startX = this.margin;
    
    const insights = [
        { title: 'Recommendation', value: analysisResult.recommendation, color: COLORS.ACCENT_BLUE },
        { title: 'Short-Term Target', value: formatPrice(parseFloat(getMetricValue(analysisResult.target_price.short_term)), currencySymbol), color: COLORS.PRIMARY_TEXT },
        { title: 'Long-Term Target', value: formatPrice(parseFloat(getMetricValue(analysisResult.target_price.long_term)), currencySymbol), color: COLORS.PRIMARY_TEXT },
        { title: 'Stop Loss', value: formatPrice(parseFloat(getMetricValue(analysisResult.stop_loss)), currencySymbol), color: COLORS.RED }
    ];

    insights.forEach((insight, i) => {
        const x = startX + i * (boxWidth + 6.5);
        this.doc.setDrawColor(COLORS.BORDER_LIGHT);
        this.doc.roundedRect(x, this.y, boxWidth, boxHeight, 5, 5, 'S');
        this.addKeyInsightBox(insight.title, insight.value, insight.color, x, boxWidth, boxHeight);
    });
    
    this.y += boxHeight + 20;
  }

  addPriceSummary(analysis: StockAnalysis, currencySymbol: string) {
    this.addPageIfNeeded(40);
    const price = formatPrice(analysis.current_price, currencySymbol);
    const change = analysis.price_change ?? 0;
    const changePercent = analysis.price_change_percentage ?? '';
    const isPositive = change >= 0;
    const changeText = `${isPositive ? '+' : ''}${formatPrice(change, currencySymbol)} (${changePercent})`;

    this.doc.setFontSize(24);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(COLORS.PRIMARY_TEXT);
    this.doc.text(price, this.margin, this.y);
    
    this.doc.setFontSize(FONT_SIZES.BODY);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(isPositive ? COLORS.GREEN : COLORS.RED);
    this.doc.text(changeText, this.margin, this.y + 15);
    
    this.y += 35;
}
  
  addRiskAnalysis(riskAnalysis: RiskAnalysis) {
      const { risk_score, risk_level, summary, key_risk_factors } = riskAnalysis;
      const riskColor = risk_score > 75 ? COLORS.RED : risk_score > 50 ? COLORS.ORANGE : risk_score > 25 ? COLORS.YELLOW : COLORS.GREEN;
      
      this.addPageIfNeeded(80);
      
      this.doc.setFontSize(FONT_SIZES.H3);
      this.doc.setTextColor(riskColor);
      this.doc.text(`Risk Score: ${risk_score}/100 (${risk_level})`, this.margin, this.y);
      this.y += 20;
      
      this.addBodyText(summary);
      
      this.addBulletedList('Key Risk Factors:', key_risk_factors, 'negative');
  }

  addCompetitiveTable(analysis: CompetitiveAnalysis, currencySymbol: string) {
    const headers = ['METRIC', 'TARGET CO.', ...analysis.competitors.map(c => c.name.toUpperCase()), 'INDUSTRY AVG.'];
    const metrics: (keyof FinancialMetrics)[] = ['market_cap', 'pe_ratio', 'pb_ratio', 'debt_to_equity', 'roe'];

    const bodyData = metrics.map(metric => {
        return [
            metric.replace(/_/g, ' ').toUpperCase(),
            getMetricValue(analysis.target_company_metrics?.[metric] ?? null),
            ...analysis.competitors.map(c => getMetricValue(c.metrics?.[metric] ?? null)),
            getMetricValue(analysis.industry_average_metrics?.[metric] ?? null),
        ];
    });

    this.addPageIfNeeded(150); // Rough estimate
    
    autoTable(this.doc, {
        head: [headers],
        body: bodyData,
        startY: this.y,
        theme: 'grid',
        styles: {
            fontSize: FONT_SIZES.SMALL,
            cellPadding: 4,
        },
        headStyles: {
            fillColor: COLORS.HEADER_BG,
            textColor: COLORS.HEADER_TEXT,
            fontStyle: 'bold',
        },
        columnStyles: {
            0: { cellWidth: 80, fontStyle: 'bold' },
        },
    });
    
    this.y = (this.doc as any).lastAutoTable.finalY + 20;
  }

   addDebateLog(critique: ChiefAnalystCritique & { refined_answer?: string }) {
        this.addPageIfNeeded(100);
        this.addSubsectionTitle("Identified Conflict");
        this.addBodyText(critique.conflict_summary);
        this.addSubsectionTitle("Remediation Question Sent To Specialist");
        this.addBodyText(`To the ${critique.target_agent} Agent: "${critique.remediation_question}"`);
        if (critique.refined_answer) {
            this.addSubsectionTitle("Refined Answer from Specialist");
            this.addCodeBlock(critique.refined_answer);
        }
        this.addSpacer(20);
    }

  addSpacer(height: number) {
    this.addPageIfNeeded(height);
    this.y += height;
  }

  save(filename: string) {
    this.addHeadersAndFooters();
    this.doc.save(filename);
  }
}

export const generateMethodologyPdf = async (
    stockSymbol: string,
    plan: string | null,
    steps: ExecutionStep[],
    sources: GroundingSource[]
) => {
    const builder = new PdfBuilder(`Methodology Report (${stockSymbol})`);
    builder.buildTitlePage('Methodology Report', stockSymbol);
    
    if (plan) {
        builder.addSectionTitle('Analysis Plan');
        builder.addBodyText(plan);
        builder.addSpacer(20);
    }

    if (sources && sources.length > 0) {
        builder.addSectionTitle('Consolidated Sources');
        builder.addSourceList(sources);
        builder.addSpacer(20);
    }
    
    builder.addSectionTitle('Execution Log');
    steps.forEach(step => builder.addStep(step));

    const filename = `Methodology_${stockSymbol}_${getFilenameTimestamp()}.pdf`;
    builder.save(filename);
};

export const generateAnalysisPdf = async (
  analysisResult: StockAnalysis,
  esgAnalysis: EsgAnalysis | null,
  macroAnalysis: MacroAnalysis | null,
  newsAnalysis: NewsAnalysis | null,
  leadershipAnalysis: LeadershipAnalysis | null,
  competitiveAnalysis: CompetitiveAnalysis | null,
  sectorAnalysis: SectorAnalysis | null,
  corporateCalendarAnalysis: CorporateCalendarAnalysis | null,
  marketSentimentAnalysis: MarketSentimentAnalysis | null,
  currencySymbol: string
) => {
    const builder = new PdfBuilder(`Financial Analysis Report (${analysisResult.stock_symbol})`);
    builder.buildTitlePage('Financial Analysis Report', analysisResult.share_name || analysisResult.stock_symbol);
    
    // --- Key Insights & Risk ---
    builder.addSectionTitle('Key Insights & Recommendation');
    builder.addPriceSummary(analysisResult, currencySymbol);
    builder.addKeyInsightsGrid(analysisResult, currencySymbol);
    if (analysisResult.risk_analysis) {
        builder.addRiskAnalysis(analysisResult.risk_analysis);
    }
    builder.addSpacer(20);

    // --- Investment Thesis ---
    builder.addSectionTitle('Investment Thesis & Justification');
    builder.addSubsectionTitle('Overall Recommendation');
    builder.addBodyText(analysisResult.justification.overall_recommendation);
    builder.addSubsectionTitle('Confidence Rationale');
    builder.addBodyText(analysisResult.justification.confidence_rationale);
    builder.addSubsectionTitle('Nutshell Summary');
    builder.addBodyText(analysisResult.justification.nutshell_summary);
    builder.addSpacer(20);
    
    // --- Financials ---
    builder.addSectionTitle('Financial Analysis');
    builder.addSubsectionTitle('Profit & Loss Summary');
    builder.addBodyText(analysisResult.justification.profit_and_loss_summary);
    builder.addSubsectionTitle('Balance Sheet Summary');
    builder.addBodyText(analysisResult.justification.balance_sheet_summary);
    builder.addSubsectionTitle('Financial Ratios Summary');
    builder.addBodyText(analysisResult.justification.financial_ratios_summary);
    builder.addSpacer(20);

    // --- Detailed Contextual Summaries from Agents ---
    builder.addSectionTitle('Detailed Specialist Agent Analysis');
    if (esgAnalysis) {
        builder.addSubsectionTitle('ESG Analysis');
        builder.addKeyValueGrid({
            'ESG Score': esgAnalysis.score,
            'Momentum': esgAnalysis.esg_momentum,
            'Confidence': esgAnalysis.score_confidence || 'N/A',
            'Last Updated': formatDate(esgAnalysis.last_updated),
        });
        builder.addBodyText(esgAnalysis.justification.overall_summary);
    }
    if (macroAnalysis) {
        builder.addSubsectionTitle('Macroeconomic Analysis');
        builder.addKeyValueGrid({
            'GDP Growth': macroAnalysis.gdp_growth,
            'Inflation Rate': macroAnalysis.inflation_rate,
            'Interest Rate': macroAnalysis.interest_rate
        });
        builder.addBodyText(macroAnalysis.outlook_summary);
    }
     if (marketSentimentAnalysis) {
        builder.addSubsectionTitle('Market Sentiment Analysis');
        builder.addKeyValueGrid({'Overall Sentiment': marketSentimentAnalysis.overall_sentiment});
        builder.addBodyText(marketSentimentAnalysis.sentiment_summary);
        builder.addBulletedList('Positive Points', marketSentimentAnalysis.key_positive_points, 'positive');
        builder.addBulletedList('Negative Points', marketSentimentAnalysis.key_negative_points, 'negative');
    }
    if (newsAnalysis) {
        builder.addSubsectionTitle('News Analysis');
        builder.addKeyValueGrid({'Overall Sentiment': newsAnalysis.overall_sentiment});
        builder.addBodyText(newsAnalysis.summary);
    }
     if (leadershipAnalysis) {
        builder.addSubsectionTitle('Leadership Analysis');
        builder.addKeyValueGrid({'Overall Assessment': leadershipAnalysis.overall_assessment});
        builder.addBodyText(leadershipAnalysis.summary);
    }
    if (competitiveAnalysis) {
        builder.addSubsectionTitle('Competitive Analysis');
        builder.addBodyText(competitiveAnalysis.competitive_summary);
        builder.addCompetitiveTable(competitiveAnalysis, currencySymbol);
    }
    if (sectorAnalysis) {
        builder.addSubsectionTitle('Sector Analysis');
        builder.addKeyValueGrid({'Sector Outlook': sectorAnalysis.sector_outlook});
        builder.addBodyText(sectorAnalysis.summary);
        builder.addBulletedList('Key Drivers', sectorAnalysis.key_drivers, 'positive');
        builder.addBulletedList('Key Risks', sectorAnalysis.key_risks, 'negative');
    }
    if (corporateCalendarAnalysis) {
        builder.addSubsectionTitle('Corporate Calendar');
        builder.addKeyValueGrid({
            'Next Earnings': corporateCalendarAnalysis.next_earnings_date,
            'Ex-Dividend Date': corporateCalendarAnalysis.dividend_ex_date,
            'Analyst Day': corporateCalendarAnalysis.analyst_day_date
        });
        builder.addBodyText(corporateCalendarAnalysis.summary);
    }
    builder.addSpacer(20);
    
    // --- Debate Log ---
    if (analysisResult.chiefAnalystCritique) {
        builder.addSectionTitle("Chief Analyst's Debate Log");
        builder.addDebateLog(analysisResult.chiefAnalystCritique);
    }
    
    const filename = `Analysis_${analysisResult.stock_symbol}_${getFilenameTimestamp()}.pdf`;
    builder.save(filename);
};